//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class batch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public batch()
        {
            this.resistrations = new HashSet<resistration>();
        }
    
        public int id { get; set; }
        [Display(Name = "Batch Name")]
        [Required(ErrorMessage = "Please enter the batch name ")]
        public string batch1 { get; set; }
        [Display(Name = "Batch year")]
        [Required(ErrorMessage = "Please enter the year of batch ")]
        public string year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resistration> resistrations { get; set; }
    }
}
